source 'https://rubygems.org'
ruby '2.5.0'
gem 'bcrypt'
gem 'bootstrap-sass'
gem 'coffee-rails'
gem 'faker'
gem 'font-awesome-rails'
gem 'gpx'
gem 'jbuilder'
gem 'jquery-rails'
gem 'pg'
gem 'rails'
gem 'listen'
gem 'sass-rails'
gem 'simple_form'
gem 'tzinfo-data'
gem 'uglifier'

group :test do
  gem 'rspec-rails'
  gem 'factory_girl'
end
