development: &development
  adapter: postgresql
  database: runaway_dev
  username: postgres
  password: postgres
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: runaway_test

production:
  <<: *development
  database: runaway_prod
